FROM loghi/docker.htr
RUN rm -rf \
    /usr/lib/x86_64-linux-gnu/libcuda.so* \
    /usr/lib/x86_64-linux-gnu/libnvcuvid.so* \
    /usr/lib/x86_64-linux-gnu/libnvidia-*.so* \
    /usr/lib/x86_64-linux-gnu/libcudadebugger.so* \
    /usr/lib/firmware \
    /usr/local/cuda/compat/lib

